### ISSUE TITLE
The type-family.scss design token cannot load the fonts from the asset

### ISSUE THREAD

**Issue by jazzgrewal** [bcgov/nr-fsa-theme#40]
While using the type-family.scss file in our apps custom.scss it gives error that it cannot find the font files.
![Screenshot 2023-05-26 at 10 26 11 AM](https://github.com/bcgov/nr-fsa-theme/assets/39718912/222c9795-9569-4eac-bc3f-c9670495903f)

**Comment by MCatherine1994** [comment]
fixed in #41
