### ISSUE TITLE
Derek to help figure out notifications when we (re)assign tickets to people

### ISSUE THREAD

**Issue by jackwingsam** [bcgov/nr-fsa-theme#62]
@DerekRoberts

**Comment by jackwingsam** [comment]
@MCatherine1994 @jazzgrewal @kevinginley @alkolot

False alarm. Notifications seem to work as expected. 

Github is smart enough to not send an email to someone who assigns themselves a ticket so we wrongly assumed notifications were not working when an email did not appear.

**Comment by DerekRoberts** [comment]
@jackwingsam Glad that just plain noticing this thing counts as work.  ;)
